### ISSUE TITLE
Slackでメッセージが削除されると落ちる

### ISSUE THREAD

**Issue by yakumo-saki** [mstdn-workers/oppai_counter#1]
mes_list内にnilが紛れ込んでしまう。
edit時と同じようにスルーする等の対応が必要

**Comment by yakumo-saki** [comment]
ff9fab5
eb2a908

**Comment by ryoana14** [comment]
editとdeleteの場合はJSONにsubtypeが含まれるようなので無視するようにしましたー

**Comment by ryoana14** [comment]
動作確認おけー
